using Calendar.Core;

namespace Calendar.Api.Ai;

/// <summary>
/// Provides deterministic local previews for the documented <c>sample: dinner-and-picnic</c> input.
/// </summary>
public sealed class FakeCalendarTextInterpreter : ICalendarTextInterpreter
{
    /// <inheritdoc/>
    public Task<CalendarTextInterpretationResult> InterpretAsync(
        CalendarTextInterpretationInput input,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(input);
        cancellationToken.ThrowIfCancellationRequested();

        if (!string.Equals(input.Text.Trim(), "sample: dinner-and-picnic", StringComparison.OrdinalIgnoreCase))
        {
            return Task.FromResult(new CalendarTextInterpretationResult(
                [],
                [],
                ["Fake mode accepts only 'sample: dinner-and-picnic'."]));
        }

        var localNow = TimeZoneInfo.ConvertTime(input.CurrentInstant, input.TimeZone);
        var tomorrow = localNow.Date.AddDays(1);
        var dinnerStart = new DateTimeOffset(tomorrow.AddHours(18), input.TimeZone.GetUtcOffset(tomorrow.AddHours(18)));
        var picnicStart = new DateTimeOffset(tomorrow.AddDays(1), input.TimeZone.GetUtcOffset(tomorrow.AddDays(1)));
        IReadOnlyList<CalendarEventCreateRequest> drafts =
        [
            new("Dinner", null, "Home", dinnerStart, dinnerStart.AddHours(1), false, []),
            new("Picnic", null, null, picnicStart, picnicStart.AddDays(1), true, [])
        ];

        return Task.FromResult(new CalendarTextInterpretationResult(
            drafts,
            ["This preview was generated by the deterministic fake provider."],
            []));
    }
}